<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person">
		<email>gentoo@houseofsuns.org</email>
		<name>Markus Walter</name>
	</maintainer>
	<longdescription>|Build| |Status| |PyPiVersion| |License| |Downloads|Introduction------------By design asyncio `does not allow &lt;https://bugs.python.org/issue22239&gt;`_its event loop to be nested. This presents a practical problem:When in an environment where the event loop isalready running it's impossible to run tasks and waitfor the result. Trying to do so will give the error&quot;``RuntimeError: This event loop is already running``&quot;.The issue pops up in various environments, such as web servers,GUI applications and in Jupyter notebooks.This module patches asyncio to allow nested use of ``asyncio.run`` and``loop.run_until_complete``.Installation------------.. code-block::    pip3 install nest_asyncioPython 3.5 or higher is required.Usage-----.. code-block:: python    import nest_asyncio    nest_asyncio.apply()Optionally the specific loop that needs patching can be givenas argument to ``apply``, otherwise the current event loop is used.An event loop can be patched whether it is already runningor not. Only event loops from asyncio can be patched;Loops from other projects, such as uvloop or quamash,generally can't be patched... |Build| image:: https://github.com/erdewit/nest_asyncio/workflows/Test/badge.svg?branche=master   :alt: Build   :target: https://github.com/erdewit/nest_asyncio/actions.. |PyPiVersion| image:: https://img.shields.io/pypi/v/nest_asyncio.svg   :alt: PyPi   :target: https://pypi.python.org/pypi/nest_asyncio.. |Status| image:: https://img.shields.io/badge/status-stable-green.svg   :alt:.. |License| image:: https://img.shields.io/badge/license-BSD-blue.svg   :alt:.. |Downloads| image:: https://pepy.tech/badge/nest-asyncio/month   :alt: Number of downloads   :target: https://pepy.tech/project/nest-asyncio</longdescription>
</pkgmetadata>